[sdl]
fullscreen=false
autolock=false
[autoexec]
mount c "C:\Users\HP\Documents\GitHub\assembly-lowlevel\Assembly Language Dry Running Tool Project\afd-toolchain"
c:
nasm.exe USERPROG.ASM -fbin -o USERPROG.COM -EUSERPROG.ERR
exit
