[sdl]
fullscreen=false
autolock=false
windowresolution=1024x768
output=surface
[autoexec]
mount c "C:\Users\HP\Documents\GitHub\assembly-lowlevel\Assembly Language Dry Running Tool Project\afd-toolchain"
c:
cls
afd.exe USERPROG.COM
